language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
notifications:
    slack: astrochats:tV2KNwL9jXSGSv5KhulGNVro
git:
    depth: 3

# Setup anaconda
before_install:
# Install packages
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda;
install:
    - conda update setuptools
    - conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib mpi4py scipy jupyter
    - pip install coveralls
    - xargs -L 1 pip install < requirements.txt
    - coverage run -p setup.py install

# Run test
script:
    - echo "travis_fold:start:FIT Fitting test data"
    - mpirun -np 2 coverage run -p --source=mosfit -m mosfit -e SN2006le --travis -i 1 -f 1 -p 0
    - mpirun -np 2 coverage run -p --source=mosfit -m mosfit -e SN2006le.json --travis -i 1 --no-fracking -m magnetar
    - mpirun -np 2 coverage run -p --source=mosfit -m mosfit -e LSQ12dlf --travis -i 1 --no-fracking -m csm
    - mpirun -np 2 coverage run -p --source=mosfit -m mosfit -e LSQ12dlf --travis -i 1 --no-fracking -m rprocess
    - coverage run -p --source=mosfit -m mosfit -e SN2007bg --travis -i 1 --no-fracking -m ic
    - coverage run -p --source=mosfit -m mosfit -e LSQ12dlf --travis -i 1 --no-fracking -m slsn -S 20 -E 10.0 100.0
    - coverage run -p --source=mosfit -m mosfit -e 2010kd --travis -i 5 --no-fracking -m slsn --extra-bands u g --extra-instruments LSST -L 55540 55560 --exclude-bands B -s test --quiet -u
    - echo "travis_fold:end:FIT Fitting test data done"
    - echo "travis_fold:start:GEN Generating random models"
    - coverage run -p --source=mosfit -m mosfit --travis -i 0
    - coverage run -p --source=mosfit -m mosfit -i 0 -m default -P parameters_test.json
    - echo "travis_fold:end:GEN Generating random models done"
    - echo "travis_fold:start:JUP Testing Jupyter notebooks"
    - echo "travis_fold:end:JUP Testing Jupyter notebooks"
    - coverage combine

# Run coveralls
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi
