language: python
python:
    - "3.4"
    - "3.5"
notifications:
    email:
        on_failure: change
        on_success: change
git:
    depth: 3

# Setup anaconda
before_install:
# Install packages
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-4.0.5-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - if [[ "$TRAVIS_PYTHON_VERSION" != "3.3" ]];
      then conda update -q conda;
      fi
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib
    - pip install -r requirements.txt
    - pip install coveralls

# Run test
script:
    - echo "travis_fold:start:IMPORT Fitting test data"
    - coverage run -a -m friendlyfit
    - echo "travis_fold:end:IMPORT Fitting test data done"

# Run coveralls
after_success:
    coveralls
